version: '2'

services:
  mysql:
    container_name: testmsdb
    image: mysql:5.7
    user: "1000:50"
    expose:
      - 3306
    ports:
      - "33060:3306"
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "./schema.sql:/schema.sql"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testms
    command: "--init-file /schema.sql"